getsentry/action-release

package.json, src/cli.ts
When a release is created with the Github Action, Sentry gets told about it via the User Agent string.
=> Add SENTRY_PIPELINE to GitHub Action

README.md, __tests__/main.test.ts, src/validate.ts
If the users passes in `${{github.ref}}`, then strip off the unwanted `"refs/tags/"` prefix.
=> Strip ref from version

README.md, __tests__/main.test.ts, action.yml, src/validate.ts
Allow users to set a prefix to the automatically generated version. For example prepend `version-` to the hash to get `version-444d9525595959e430e19729ca9e125ed786c756`.
=> Release Prefix

__tests__/main.test.ts, action.yml, src/main.ts, src/validate.ts
This PR adds a new option for setting commits: `set_commits`. Currently, it only takes two values: `auto` and `skip`. If no value is provided, we pick `auto`. When `auto` is provided, we automatically try to associate commits with the users' source code provider that's installed. If `skip` is provided, we just don't set commits.
Resolves https://github.com/getsentry/action-release/issues/21
=> feat: add set commits option

__tests__/main.test.ts, action.yml, package.json, src/main.ts, src/sentry-cli.d.ts, src/validate.ts, yarn.lock
This PR allows creating a release on multiple projects at once with a space-separated list of projects. Here's how you'd configure that in your `deploy.yml` file:
```
- name: Sentry Release
uses: getsentry/action-release@v1
with:
projects: project1 project2
```
If you specify `projects`, then it does not read the project from the environment variable `SENTRY_PROJECT` which is not required. Conversely, if you omit `projects` then `SENTRY_PROJECT` is still required.
Fixes: https://github.com/getsentry/action-release/issues/29
=> feat: multiple project options

README.md, __tests__/main.test.ts, package.json, src/main.ts, src/validate.ts
This PR adds a new option for the URL prefix used for source maps: `url_prefix`. Example:
```
- name: Sentry Release
uses: getsentry/action-release@v1
with:
environment: production
sourcemaps: build/static/js
url_prefix: ~/static/js
```
This option adds a prefix to the source map URLs after stripping them.
I also updated the readme with the new project options which I apparently missed before.
=> feat: url prefix for source maps

README.md, action.yml, src/main.ts, src/validate.ts
Made `environment` input parameter optional.
Issue #19
=> make environment input parameter optional

action.yml
Seems like `action.yml` is missing the `url_prefix` input, which causes Github to throw a warning:
=> Adds missing url_prefix input in action.yml

README.md
I am using Self-Hosted Sentry. 
README didn't include instructions for creating a release on Self-Hosted Sentry, so I have added them.
ref. https://docs.sentry.io/product/cli/configuration/#configuration-file
=> [Doc] Write example for Self-Hosted Sentry

.github/ISSUE_TEMPLATE/release-checklist.md, README.md
In order to make sure that we follow all steps to create a release I've created a new template and this makes reference to it.
I've merged the template to `master` without thinking about it. Please have a look at it and let me know if you want some tweaks:
https://github.com/getsentry/action-release/commit/8b4720d3d1512cfb105c59518acd3bd52c6323e6
=> feat: Add link to new release issue creation

package.json
This does not actually make a release but when making a release we will make reference to this commit.
Since it is not a security release we will tag it as a minor update.
Release draft:
=> ref: New package version to indicate the beginning of a new release

.github/ISSUE_TEMPLATE/bug-report.md
Since we defined our own release checklist template, we don't get the default org-level bug report template.
=> feat: Add bug report issue template

package.json, yarn.lock
Looking at releases I don't see anything that suggests this update will break anything.
https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md
=> Update actions/core to address github deprecations

package.json
https://github.com/getsentry/action-release/issues/111
Minor bump feels appropriate as this release is largely a bump in dependencies with no expected behavioral changes.
We could go to v2.0.0 to be on the safe side
=> Update version to 1.2.1

.github/actions/use-local-dockerfile/action.yml, .github/workflows/test.yml, README.md, action.yml, src/main.ts, src/options.ts
When running the action-release Github Action, occasionally one might need to perform auto-detection of associated commits in a directory other than the job's working directory, such as in the case where an action performs multiple checkouts. As Github Actions do not, by default, support the ability to run an action in any directory other than the job's working directory, this change implements an argument for specifying which directory to gather sentry release information from.
Implements #117 .
=> feat: implement 'working-directory' argument

README.md, __tests__/main.test.ts, action.yml, src/main.ts, src/options.ts
Adds support for `dist` as input value for GitHub Action:
```yaml
- uses: getsentry/action-release@v1
with:
environment: 'production'
sourcemaps: './lib'
dist: ${{ github.sha }}
```
Note that this repo uses `@sentry/cli@^1.67.2` and there is a related fix in `2.3.1`:
> fix: move dist option to SentryCliUploadSourceMapsOptions (#1269) by @ikenfin
> [changelog](https://github.com/getsentry/sentry-cli/blob/master/CHANGELOG.md#231)
The above `sentry-cli` fix was to move the `dist` option from being under `SentryCliOptions` (incorrect) to be under `SentryCliUploadSourceMapsOptions` (correct)
This does not affect the GH action as those types are not referenced directly by the action.
Have not added tests for the value being passed to the CLI as that doesn't appear to be covered for any of the …
=> feat: Add option to set `dist` on sourcemaps

README.md, __tests__/main.test.ts, src/options.ts
In #125, we added support for using `dist` with sourcemaps, however, we return `null` when not specified and that gets converted into the string `"null"` down the pipeline which has broken the sourcemaps for various customers in the last two weeks.
Also, ss indicated in #138, `dist` is optional for sourcemaps when used with the CLI. Updating the README.me to handle it.
This also removes a warning which shows when the action is run:
```
Warning: Unexpected input(s) 'dist', valid inputs are ['entryPoint', 'args', 'environment', 'sourcemaps', 'finalize', 'ignore_missing', 'ignore_empty', 'started_at', 'version', 'version_prefix',
'set_commits', 'projects', 'url_prefix', 'strip_common_prefix', 'working_directory']
```
Fixes #140
=> fix: dist option should be undefined if not specified

.github/CODEOWNERS, README.md
Our team will not maintain this repo anymore. I'm also moving the troubleshooting section to the bottom.
Also some minor tweaks to these sections:
=> ref: Remove codeowners and update docs

.github/workflows/build.yml, .github/workflows/test.yml, README.md
For PRs, the CI will create releases under the action-release-prs project while master will create them for the action-release project.
We use different projects since the Release feature does not handle different environments as a way to separate commits. Alternatively, we could have postfixed a different string per PR and use the same project.
This PR also enable us to test real action-release execution (read: end to end testing).
=> ci: End to end testing

__tests__/main.test.ts
If the timezone isn't specified, the timestamp will be parsed depending on local time, which makes the test fail.
=> fix(test): Add timezone to timestamp

.github/workflows/build.yml
You can see this PR working [here](https://github.com/getsentry/action-release/actions/runs/4833388053/jobs/8613330988?pr=155).
If the action executes and there's never been a release before, it will fail. Adding `ignore_missing` fixes it:
```
When the flag is set and the previous release commit was not found in the repository, will create a release with the default commits count instead of failing the command.
```
=> fix(ci): Allow create default set of commits

.github/workflows/build.yml
=> Multi-arch docker image

.eslintrc.json, README.md, action.yml, package.json, src/cli.ts, src/main.ts, src/options.ts, src/telemetry.ts, tsconfig.json, yarn.lock
Adds telemetry by setting up a barebones Sentry instance using `@sentry/node`. Individual steps can be traced by wrapping them with the `traceStep` helper.
Here's an [example of an execution](https://sentry.sentry.io/performance/trace/e40880d3a70b621bbcfa5dff9e6d350b/?dataset=transactions&field=title&field=project&field=user.display&field=timestamp&fov=0%2C4356&name=All%20Errors&node=txn-cd9a955244d044f5890325c9de62355c&project=4508608809533441&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=5m&timestamp=1736430518&yAxis=count%28%29):
Closes: #214
=> feat(telemetry): Add telemetry via `@sentry/node`

package.json
Note: the version change here is quite drastic because it was overlooked that we should also bump the package version here. The latest version of the action is `1.7.0`: https://github.com/marketplace/actions/sentry-release
Ref: https://github.com/getsentry/action-release/issues/216
=> meta(release): Bump version to 1.8.0

src/main.ts, src/telemetry.ts
Collects
- `project: string` if single project is specified
- `projects: string[]` if multiple projects are specified, comma-separated
- `set-commits: 'auto' | 'skip'`
- `sourcemaps: boolean` if sourcemaps are set by the user
- `sourcemaps-uploaded: true` iff sourcemaps have been uploaded, not set otherwise
- `finalized: true` iff release has been finalized
- `organization: string` the user org
It also sets the `user.id` to the user org.
ref: https://github.com/getsentry/action-release/issues/217
Some of the tags listed in the reference issue have not been collected:
- `project id`, not available -> only project slug is collected
- `action release version` -> already collected
- `checkout action version` -> we do not have access to this
- `platform` -> we do not have access to this in the …
=> feat(telemetry): Collect project specific tags

README.md, action.yml, docs/publishing-a-release.md, package.json, src/main.ts
`inject` is off by default in this version. We are considering making it opt-out by default in the near future.
Closes: #220
<hr>
From my manual test run:
=> feat(sourcemaps): Add `inject` option to inject debug ids into source files and sourcemaps

README.md
Small refactor to make it clearer what secrets need to be set.
=> ref(docs): Update README with more info on prerequisites

.craft.yml, .github/actions/use-local-dockerfile/action.yml, .github/workflows/build.yml, .github/workflows/release.yml, .prettierrc.json, CHANGELOG.md, action.yml, docs/development.md, docs/publishing-a-release.md, package.json, scripts/craft-pre-release.sh
Previously, any push to `master` builts and uploads the action's underlying docker image to the GitHub registry under the `latest` tag. That meant, regardless of version specified in a user's workflow they'd get the latest change.
The introduction of craft allows us to push versioned images to the registry and associate a release's action with that version.
At the moment, this workflow does not incorporate tags for major (e.g. `v1`) and major.minor (e.g. `v1.2`). The ability to publish several git tags will probably have to be added to craft or publish directly.
Closes: #129, #233
=> chore(release): Add craft publish workflow

.craft.yml
We don't publish any artifacts when releasing, everything is done via the docker registry. Not turning this off results in Craft trying to look up artifacts, example failed run: https://github.com/getsentry/publish/actions/runs/13032284844?check_suite_focus=true#step:8
=> chore(release): Unset artifactProvider in craft

.craft.yml
The targets to publish the final docker image has been wrongly defined.
=> fix(craft): Fix craft target to publish to github registry

.github/workflows/test.yml, CHANGELOG.md, __tests__/main.test.ts, src/options.ts
=> fix: Ensure working directory always starts out at repo root

action.yml
Not all runners have npm/yarn out of the box so unfortunately we'll have to ensure both node and npm are available using volta. 
Closes: #253
=> fix(ci): Use volta to ensure node and npm are available

README.md, action.yml
The action now first checks if node is already installed and if so skips `action/setup-node`, otherwise we ensure node (and thus npm) are installed before running the action.
Additionally, it also marks the `GITHUB_WORKSPACE` as a safe directory for git so the runner can correctly cd into the repo root for automatic release name determination and commit blaming.
Closes: #249
=> fix(action): Use `action/setup-node` instead of unofficial volta action

.github/workflows/build.yml, action.yml
Previously, when the CI triggers for master, the action changes the docker tag back from whatever was committed in a branch to `master` and commits and pushes this change back to the master branch.
However, because the job is run ist run twice, once for the builder docker image and once for the app docker image, that step was executed twice, trying to commit and push twice.
We only want to do this once, so I extracted this up into its own job that the building job depends on.
=> fix(ci): Move updating docker tag into own job to avoid setting it twice per run: when the builder image is built and when the app image is built

.github/workflows/build.yml, action.yml
Noticed CI still runs when the action switches back the docker tag to master. According to https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs the label should be `[skip ci]` not `[skip-ci]`.
=> fix(ci): Use correct label to skip ci on master runs

.pre-commit-config.yaml, CHANGELOG.md, README.md, action.yml, src/main.ts
This PR will flip the default value of `inject` from `false` to `true` to inject Debug IDs by default when users specify `sourcemaps`.
This is a breaking change and requires a new major.
Closes: #221
=> feat(sourcemaps)!: Enable injecting debug ids by default

CHANGELOG.md, README.md, __tests__/main.test.ts, action.yml, src/main.ts, src/options.ts
`version` (and `version_prefix`) have been confusing to users. In our SDKs, we use the parameter `release`.
This PR adds `release*` versions of both parameters and deprecates the old ones to be removed in a future version.
Closes: https://github.com/getsentry/action-release/issues/40
=> feat: Add `release` and `release_prefix` in favor of `version` and `version_prefix` 

CHANGELOG.md, action.yml
Forgot to add the PR number to the changelog.
=> meta(changelog): Update changelog for 3.1.0

.prettierrc.json, __tests__/main.test.ts, action.yml, src/cli.ts, src/main.ts, src/options.ts, src/telemetry.ts
Please see 511c3f336b17a1b394c793d5919d16ba64886ecd for the relevant changes.
<hr/>
I also reworked how projects are passed to the CLI. Previously the CLI was invoked once per project, but I saw that sentry-cli does actually support passing multiple projects so I reworked that.
Here's a screenshot from the report email showing the two projects I specified in a private repo.
<hr/>
Closes: #137
=> fix: Only pass `urlPrefix` to sentry-cli if it's not empty 

.github/workflows/build.yml, CHANGELOG.md, action.yml
The action now saves and restores the original Node version when running on macOS and Windows runners, preventing it from permanently changing the Node version for subsequent workflow steps. This ensures the action doesn't interfere with other steps that may require a specific Node version.
Fixes: #279
=> fix: Preserve existing Node version on macOS and Windows runners

.github/workflows/release.yml, action.yml
Can't release because `ubuntu-20.04` has been [removed in April](https://github.com/actions/runner-images/issues/11101).
=> chore: Update release runner to `ubuntu-latest`
